/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cn.shouma.bsytest;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int possible_result_points=0x7f050002;
        public static final int result_view=0x7f050000;
        public static final int viewfinder_mask=0x7f050001;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int mm_title_back_btn=0x7f020001;
        public static final int mm_title_back_focused=0x7f020002;
        public static final int mm_title_back_normal=0x7f020003;
        public static final int mm_title_back_pressed=0x7f020004;
        public static final int mmtitle_bg_alpha=0x7f020005;
    }
    public static final class id {
        public static final int about_version_code=0x7f07000e;
        public static final int action_settings=0x7f070056;
        /**  Messages IDs 
         */
        public static final int auto_focus=0x7f070000;
        public static final int btnShanChu=0x7f07003c;
        public static final int btnShangChuan=0x7f07003d;
        public static final int btn_ShouYeCollect=0x7f070018;
        public static final int btn_ShouYeDownload=0x7f070017;
        public static final int btn_baseData=0x7f070016;
        public static final int btn_cancel=0x7f070048;
        public static final int btn_commit=0x7f070047;
        public static final int btn_erWeiMaLook=0x7f07002a;
        public static final int btn_erWeiMaScan=0x7f070029;
        public static final int btn_port=0x7f070019;
        public static final int btn_selectAll=0x7f070046;
        public static final int button_back=0x7f07001a;
        public static final int checkBox1=0x7f07004b;
        public static final int decode=0x7f070001;
        public static final int decode_failed=0x7f070002;
        public static final int decode_succeeded=0x7f070003;
        public static final int ed_FaHuonumber=0x7f07002d;
        public static final int ed_amount=0x7f070034;
        public static final int ed_businessman=0x7f070032;
        public static final int ed_clientName=0x7f07002e;
        public static final int ed_productName=0x7f070030;
        public static final int ed_productNumber=0x7f07002f;
        public static final int ed_productStandard=0x7f070031;
        public static final int ed_scanAmount=0x7f070035;
        public static final int ed_type=0x7f070033;
        public static final int encode_failed=0x7f070004;
        public static final int encode_succeeded=0x7f070005;
        public static final int gridview=0x7f07000c;
        public static final int hs_basedatalist=0x7f070025;
        public static final int hs_goodscollect=0x7f070039;
        public static final int hs_goodslist=0x7f070049;
        public static final int il_baseDataTitleBar=0x7f070026;
        public static final int il_goodsCollectTitleBar=0x7f07003a;
        public static final int include1=0x7f070012;
        public static final int launch_product_query=0x7f070006;
        public static final int linear_layout_up=0x7f07001c;
        public static final int llBottom=0x7f070028;
        public static final int llFromtitle=0x7f070021;
        public static final int llOptions=0x7f070015;
        public static final int ll_editor=0x7f07003b;
        public static final int lvList=0x7f07004a;
        public static final int lv_baseData_List=0x7f070027;
        public static final int lv_content=0x7f070053;
        public static final int preview_view=0x7f070010;
        public static final int quit=0x7f070007;
        public static final int restart_preview=0x7f070008;
        public static final int return_scan_result=0x7f070009;
        public static final int rlShouYeTitle=0x7f070013;
        public static final int rlTitleBar=0x7f070043;
        public static final int rl_baseData_TitleBar=0x7f070022;
        public static final int rl_collectdetail_TitleBar=0x7f07002b;
        public static final int rl_goodsCollect_TitleBar=0x7f070037;
        public static final int search_book_contents_failed=0x7f07000a;
        public static final int search_book_contents_succeeded=0x7f07000b;
        public static final int split=0x7f07000f;
        public static final int textview_title=0x7f07001b;
        public static final int tvBack=0x7f070044;
        public static final int tvSelectedItem=0x7f070045;
        public static final int tvTitle=0x7f070014;
        public static final int tv_barcode=0x7f070052;
        public static final int tv_barcodeContent=0x7f070036;
        public static final int tv_barcode_item=0x7f070055;
        public static final int tv_baseData_Back=0x7f070023;
        public static final int tv_baseData_download=0x7f070024;
        public static final int tv_basedata_tuozhan1=0x7f070020;
        public static final int tv_clientName=0x7f07004d;
        public static final int tv_collect_Back=0x7f07002c;
        public static final int tv_collect_pCode=0x7f07003f;
        public static final int tv_collect_pGZ=0x7f070040;
        public static final int tv_collect_pName=0x7f07003e;
        public static final int tv_collect_tuozhan1=0x7f070041;
        public static final int tv_collect_tuozhan2=0x7f070042;
        public static final int tv_goodsCollect_Back=0x7f070038;
        public static final int tv_goodsNumbers=0x7f07004c;
        public static final int tv_goodslist_tuozhan1=0x7f07004f;
        public static final int tv_goodslist_tuozhan2=0x7f070050;
        public static final int tv_pCode=0x7f07001e;
        public static final int tv_pGZ=0x7f07001f;
        public static final int tv_pName=0x7f07001d;
        public static final int tv_saveName=0x7f07004e;
        public static final int tv_sendcodeId=0x7f070051;
        public static final int tv_sendcodeId_item=0x7f070054;
        public static final int viewfinder_view=0x7f070011;
        public static final int webview=0x7f07000d;
    }
    public static final class layout {
        public static final int activity_capture=0x7f030000;
        public static final int activity_main=0x7f030001;
        public static final int activity_title=0x7f030002;
        public static final int basedata_activity_item=0x7f030003;
        public static final int basedata_layout=0x7f030004;
        public static final int basedatalist_activity=0x7f030005;
        public static final int collectdetail_activity=0x7f030006;
        public static final int fromtitle_layout=0x7f030007;
        public static final int goodscollect_activity=0x7f030008;
        public static final int goodscollect_activity_item=0x7f030009;
        public static final int goodscollect_layout=0x7f03000a;
        public static final int goodslist_activity=0x7f03000b;
        public static final int goodslist_activity_item=0x7f03000c;
        public static final int look_activity=0x7f03000d;
        public static final int look_item=0x7f03000e;
    }
    public static final class menu {
        public static final int main=0x7f0a0000;
    }
    public static final class raw {
        public static final int beep=0x7f040000;
        public static final int bsy=0x7f040001;
        public static final int realm_properties=0x7f040002;
    }
    public static final class string {
        public static final int action_settings=0x7f080001;
        public static final int app_name=0x7f080000;
        public static final int hello_world=0x7f080002;
        public static final int scan_text=0x7f080003;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f090000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f090001;
    }
}
